let firstUserName = "Alisher";
let firstUserPoint = "97";
let Data = `${firstUserName} ${firstUserPoint} баллов из 100`;
console.log(Data);

let secondUserName = "Nooruz";
let secondUserPoint = "89";
let Data1 = `${secondUserName} ${secondUserPoint} баллов из 100`;
console.log(Data1);

let thirdUserName = "Jakshylyk ";
let thirdUserPoint = "75";
let Data2 = `${thirdUserName} ${thirdUserPoint} баллов из 100`;
console.log(Data2);

let fourthUserName = "Aziret ";
let fourthUserPoint = "90";
let Data3 = `${fourthUserName} ${fourthUserPoint} баллов из 100`;
console.log(Data3);

let text1 = "Экзамендин ";
let text2 = "орточо";
let text3 = " баллы:";
let text4 = "87.75";
console.log(`${text1} ${text2} ${text3} ${text4}`);

let Number1 = "1 x 4 = 4";
console.log(Number1);

let Number2 = "2 x 4 = 8";
console.log(Number2);

let Number3 = "3 x 4 = 12";
console.log(Number3);

let Number4 = "4 x 4 = 16";
console.log(Number4);

let Number5 = "5 x 4 = 20";
console.log(Number5);

let Number6 = "6 x 4 = 24";
console.log(Number6);

let Number7 = "7 x 4 = 28";
console.log(Number7);

let Number8 = "8 x 4 = 32";
console.log(Number8);

let Number9 = "9 x 4 = 36";
console.log(Number9);

let Number10 = "10 x 4 = 40";
console.log(Number10);


alert("Вы успешно зарегистрировались!");

console.log(
  confirm(
    "При перезагрузке сайта, введённые данные на форме будут очищены, Вы уверены что хотите перезагрузить?"
  )
);

let daniel = prompt("Введите ваше имя?");
console.log(daniel);
